# Site settings
title: Alex Lindsay
email: alexlindsay239@gmail.com
description: "Website of Alex Lindsay, computational scientist."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lindsayad.github.io" # the base hostname & protocol for your site
github_username: lindsayad

# Agency color settings
color:
  primary: e87722
  primary-dark: d45d00
  secondary: 606eb2
  secondary-dark: 002058
  transparent: rgba(24,24,24,0.7)

# Build settings
markdown: kramdown
permalink: pretty

# Jekyll Scholar
scholar:
  style: chicago-author-date
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibliography

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

  repository: papers
